### ISSUE TITLE
Plural Indefinite Articles

### ISSUE THREAD

**Issue by Sub-Xaero** [rossmeissl/indefinite_article#18]
Would it be possible to support plural indefinite articles?

I.e. 
`'apple'.with_indefinite_article # => "an apple" `
`'apples'.with_indefinite_article # => "some apples"`

**Comment by rossmeissl** [comment]
@Sub-Xaero how would you detect the plural? For example, 'lens' or 'bus'?

**Comment by Sub-Xaero** [comment]
Having considered this, it's likely beyond the scope of this project. Both `ActiveSupport::Inflector` and [other gems](https://github.com/ged/linguistics/blob/master/lib/linguistics/en/pluralization.rb) seem to just maintain a dictionary of English Language irregularities. 

Seeing as I am using this in a Rails context, and the plural indefinite article is always 'some', I'm achieving this with a simple helper method.

```ruby
module GrammarHelper

  def indefinite_article(word)
    if word.singularize == word.pluralize || word == word.pluralize
      "some #{word}"
    else
      word.with_indefinite_article
    end
  end

end
```

I'm closing this. Sorry for polluting your issue log.

**Comment by rossmeissl** [comment]
@Sub-Xaero no apologies necessary, thanks for the idea!
